version: '3'

networks:
    sql-network:
        driver: bridge
    zookeeper-network:
        driver: bridge
    dynamo-network:
        driver: bridge
    
services:
    ############################# APPS ##################################                
    clientesapi:
        image: clientesapi
        image: clientesapi
        build:
            context: ./cliente
        ports:
            - "20000:80"
        networks: 
            - sql-network
        depends_on: 
            - sqlserver

    saldosworker:
        image: saldosworker
        container_name: saldosworker
        build:
            context: ./saldo
        ports:
            - "20001:80"
        networks: 
            - dynamo-network
            - zookeeper-network
        depends_on: 
            - dynamodb

    ############################# SQL SERVER ###############################                
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        volumes: 
            - ./volumes/sql-volume/sql_data:/var/opt/mssql/data
            - ./volumes/sql-volume/sql_log:/var/opt/mssql/log
            - ./volumes/sql-volume/sql_secrets:/var/opt/mssql/secrets
        environment:
            SA_PASSWORD: "Senha123"
            ACCEPT_EULA: "Y"
        networks: 
            - sql-network
        ports: 
            - "1433:1433"

    ############################# DYNAMODB ##################################
    dynamodb:
        image: amazon/dynamodb-local
        hostname: dynamodb-local
        container_name: dynamodb-local
        networks: 
            - dynamo-network
        ports:
            - "8042:8000"
            

    ############################# ZOOKEEPER #################################
    zookeeper:  
        hostname: zookeeper
        container_name: zookeeper
        image: 'bitnami/zookeeper:latest'
        networks: 
            - zookeeper-network
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
            - ZOOKEEPER_CLIENT_PORT=2181
            - ZOOKEEPER_TICK_TIME=2000

    ############################# KAFKA #####################################                
    kafka:
        image: confluentinc/cp-kafka:latest
        networks: 
            - zookeeper-network
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1